### ISSUE TITLE
Class Webfox\Xero\OauthCredentialManager does not exist

### ISSUE THREAD

**Issue by PetraBester** [webfox/laravel-xero-oauth2#1]
Hi 

When I hit the route in my url I keep on getting the error: Class Webfox\Xero\OauthCredentialManager does not exist. Although the package has been installed correctly and I can see the file does actually exists.

I followed the installation step by step. Is there something I am missing?

**Comment by hailwood** [comment]
Hmm, only thing I can think of is that perhaps composer hasn't updated it's auto-load file correctly.

Try running `composer dump-auto` and try again.

**Comment by PetraBester** [comment]
I am using Laravel framework 5.8 and php 7.3.14 

I tried running composer dump-auto, however it still did not resolve the issue.
On closer inspection I saw that the class is not initialised because of the following line (line 16)

protected Repository $cache;

This line throws the following error: 

 "syntax error, unexpected 'Repository' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)"

**Comment by hailwood** [comment]
Ah right!
Yes apologies that's a php 7.4 feature.

I'll run through in the next 24 hours to remove any 7.4 specific code and
publish a new version 👍

Or feel free to submit a pr!

**Comment by PetraBester** [comment]
Ah ok great, glad we got it then.
Thank you very much!

**Comment by hailwood** [comment]
v1.1.1 Released which should fix this issue for you @PetraBester
