### ISSUE TITLE
"Xero oauth credentials are missing"

### ISSUE THREAD

**Issue by accessTechnology** [webfox/laravel-xero-oauth2#10]
Xero authenticates, selects one organisation (I have a redundant 'demo company' unselected) and redirects to app with the error: "Xero oauth credentials are missing"

However URL seems to contain all the necessary data:

https://domain.com/xero/auth/callback?code=85c81bfe4968d969cbfff65e94e146f768514c81b73e26227d0ead70949b1733&scope=openid%20email%20profile%20accounting.contacts%20accounting.transactions%20accounting.settings&state=fdf12d58b1dc5c2de453e289fd6195b8&session_state=KwBuThRM5zwAVKoqxZhF-4yfmhXuwG3JxfQjpA2zIpk.d6547c5c6c2b28af8ce4658228116b87

Any idea where I'm going wrong?

**Comment by hailwood** [comment]
Thanks for all your work here @accessTechnology your PRs have been merged and a new version release :)

**Comment by gbrits** [comment]
By the way - if someone is stuck on this error, you likely have actual API calls that are being made uncaught by credential checks, rather than the flow of this library. Doublecheck your own code first. :)
