### ISSUE TITLE
[6.x] Implement code styling

### ISSUE THREAD

**Issue by JamesFreeman** [webfox/laravel-xero-oauth2#108]
We can use Pint or StyleCI, whats your thoughts on this @hailwood?

**Comment by hailwood** [comment]
Since we're open source I reckon we run with styleci 👍

Btw, I may be a little slow to respond for a while as I've got to move house, but I'll try get one of my colleagues to jump in and help out 🙂 you're doing a wicked job here.

**Comment by JamesFreeman** [comment]
Implemented into develop
