### ISSUE TITLE
[6.x] Release

### ISSUE THREAD

**Issue by JamesFreeman** [webfox/laravel-xero-oauth2#114]
# Outstanding items before release 

- [x] #112 (investigate)
- [x] #110
- [x] #107 
- [x] #101
- [x] #89
- [x] #119
- [x] #120 
- [x] #124 
- [x] #123

**Comment by JamesFreeman** [comment]
Here's a release notes btw: I can't actually find many breaking changes - it'll just be types I guess?


```
- Implemented StyleCI 
- Rewritten Docs to use Github pages
- Support PHP 8.4
- Added Tests
- Added 3 new Credential Managers (Model, Authenticated User Store and Array)
- Added new `AccountAPIClient` and `IdentityAPIClient` to allow for mocking API requests
- Added new Exception handling classes (added `XeroException`)
- **BREAKING** Added types on all classes and methods, migrated to using Constructor Promotion
- Added new BaseCredentialManager to aid in creating new Credential Managers quicker
- Added new `Xero` class
- Moved default routes from `/routes/routes.php` to `/routes/web.php`
- Fixed [BUG] When using multiple tenants, the tenantId from the web hooks should be used #89
```

**Comment by hailwood** [comment]
Hey @JamesFreeman,
I've done the 6.0.0 release based on the notes above.
If there's anything we've missed we can work on the release notes.

Can I reach you via your me@j... email you use for your commits?
I'd like to discuss adding you as an official maintainer of the package if you're interested?

**Comment by JamesFreeman** [comment]
> Hey @JamesFreeman, I've done the 6.0.0 release based on the notes above. If there's anything we've missed we can work on the release notes.
> 
> Can I reach you via your me@j... email you use for your commits? I'd like to discuss adding you as an official maintainer of the package if you're interested?

Yeah, feel free to drop me an email. Thanks for the offer, it's appreciated.
