### ISSUE TITLE
protected OauthCredentialManager $credentialManager; giving error in webhook.php  file

### ISSUE THREAD

**Issue by bilalswiftsolutions** [webfox/laravel-xero-oauth2#17]
when I remove this line protected OauthCredentialManager $credentialManager;  webhook get connected with xero. then it gives authrozed error. but when i put this line back it gives error "unexpected OauthCredentialManager". 
and "Webfox\Xero\Webhook doest not exists"

**Comment by hailwood** [comment]
Hi @bilalswiftsolutions v 1.3.0 has just been released which fixes this.


Regards
