### ISSUE TITLE
Can we Connect our website with multiple xero app?

### ISSUE THREAD

**Issue by bilalswiftsolutions** [webfox/laravel-xero-oauth2#23]
Is there any possibility where we can connect our website with multiple xero apps . We are using this package but by default it provided connectivity with only one xero app

**Comment by hailwood** [comment]
Xero Apps or Xero Organisations?

**Comment by bilalswiftsolutions** [comment]
Apps

**Comment by hailwood** [comment]
I would suggest telling the package to not auto register the service provider, and then inject your own service provider first to update the relevant config options for the request https://github.com/webfox/laravel-xero-oauth2/blob/master/src/XeroServiceProvider.php#L39-L44

I'm pretty curious about a usecase for using multiple applications if you have a moment to share.

**Comment by bilalswiftsolutions** [comment]
Ok I will let you know about it..
