### ISSUE TITLE
Invalid redirect_uri

### ISSUE THREAD

**Issue by sdeering** [webfox/laravel-xero-oauth2#26]
Trying to get this working on my localhost and ran into the error: "Invalid redirect_uri"

I followed all the instructions exactly!

As you can see from the screenshots.

![4-8-2020 12-16-59 PM](https://user-images.githubusercontent.com/1787454/89245752-dbb2ad00-d64c-11ea-94c3-e55218970d88.jpg)

![4-8-2020 12-19-34 PM](https://user-images.githubusercontent.com/1787454/89245724-cccbfa80-d64c-11ea-857f-5dd7bb0674d6.jpg)

Any suggestions/thoughts much appreciated!

**Comment by sdeering** [comment]
I found the issue. But you need to edit the core package file.

vendor/webfox/laravel-xero-oauth2/src/XeroServiceProvider.php:41
Remove route() function and you can then set a full URL in the config file like so:
`'redirectUri'             => config('xero.oauth.redirect_uri'),`

config/xero.php
`'redirect_uri' => env('XERO_REDIRECT_URI'),`

This issue is caused by XERO as when you enter a localhost redirect address they append the port :80 onto the url. Mofos.

Hope this helps others solve it.

**Comment by hailwood** [comment]
@sdeering if you upgrade to v2.0.0 just released you can set the config option `xero.oauth.redirect_full_url` to `true` and it won't wrap it in the `route` helper :)

You'll want to republish the config file, apart from that it should be a seamless upgrade.
