### ISSUE TITLE
Manual refresh of tokens

### ISSUE THREAD

**Issue by KadHamW** [webfox/laravel-xero-oauth2#27]
Hey again,

I am loving the package, I have been able to integrate it into my app quite well.
The only issue I am having is the 30-minute timeout of the tokens,
I am unsure whether the package is supposed to handle this seamlessly in the background, but if that is the case it is not quite working.
Instead, I am trying to create a scheduled command that will refresh my tokens.
It appears to successfully generate new tokens, but either it isn't saving it properly back to the conf or something else is going on.
I am using the DB for my cache and that is working fine with the token info being added as expected.
So far I have this in the command, although it has been through many iterations and might be flat out wrong:

```
public function handle()
    {
    Log::info('Xero Heartbeat command run');
    try {
        $credentials = app(OauthCredentialManager::class);
        $config = app(Configuration::class);
        $oldTok = $config->getAccessToken();
        $credentials->refresh();
        $config->setAccessToken($credentials->getAccessToken());
        $newTok = $config->getAccessToken();
        Log::info("Token old: " . $oldTok . ". Token new: " . $newTok);
    } catch (\throwable $e) {
        Log::info("An error occured: " . $e->getMessage());
    }
}
```

**Comment by KadHamW** [comment]
I should add that after I run the command the calls to Xero will fail until I re-authorize Xero.

**Comment by KadHamW** [comment]
It appears to be the way I check if Xero is working that is causing a problem.
When I call:

`$user = $xeroCredentials->getUser();`

After refreshing the tokens I get an undefined variable ($sid) error but Xero still appears to be happy in the backend.

**Comment by hailwood** [comment]
Hi @KadHamW,

Is this being used in a queued task?

If so that will be the issue,
The token only gets checked for refresh when it's first resolved, but of course the queue's are long lived.

You're going to want to do something like this in the `handle` method of your command - 

```php
$credentials = app(OauthCredentialManager::class);
if ($credentials->isExpired()) {
    $xeroConfig = \XeroAPI\XeroPHP\Configuration::getDefaultConfiguration();
    $credentials->refresh();
    $xeroConfig->setAccessToken($credentials->getAccessToken());
}
```

**Comment by hailwood** [comment]
@KadHamW if you upgrade to v2.0.0 just released you shouldn't need to do this anymore :)
You'll want to republish the config file, apart from that it should be a seamless upgrade.
