### ISSUE TITLE
League \ OAuth2 \ Client \ Provider \ Exception \ IdentityProviderException invalid_grant

### ISSUE THREAD

**Issue by bilalswiftsolutions** [webfox/laravel-xero-oauth2#28]
this package often give this error. in documentation they have written reconnect will fix this issue but this is not happening. 

```
League \ OAuth2 \ Client \ Provider \ Exception \ IdentityProviderException
invalid_grant
```
How to solve this issue

**Comment by hailwood** [comment]
Hi @bilalswiftsolutions,

I'll need more information to help debug this one.

**Comment by bilalswiftsolutions** [comment]
I changed secret and key after that this problem appear. bt when i clear cache. it works fine. I think it was confilct between previous and new credentials. but is going to work always?
