### ISSUE TITLE
Target class [Webfox\Xero\CacheStore] does not exist.

### ISSUE THREAD

**Issue by azam1** [webfox/laravel-xero-oauth2#29]
Not sure what is the issue I am getting this error:
Target class [Webfox\Xero\CacheStore] does not exist.

**Comment by hailwood** [comment]
Hi @azam1,

Apologies I didn't realise my IDE had updated the reademe.md file as well during some refactoring.

I've corrected the example in the Readme
https://github.com/webfox/laravel-xero-oauth2/commit/6700a9a3983f8b2fa7f7b2cf69b80baf509021ce
