### ISSUE TITLE
Connection To Xero Failed

### ISSUE THREAD

**Issue by discoveryjames** [webfox/laravel-xero-oauth2#3]
I used the example manage page, and everything seems to work initially.

Then after a few hours it shows the below: 

```
Your connection to Xero failed
Undefined property: stdClass::$sid
```

If I click reconnect it does reconnect, but is there a reason the connection isn't being retained?

**Comment by hailwood** [comment]
Hi @discoveryjames,

The system uses Laravels Cache to store the token forever. The only two times it should reset the connection are if the token is revoked in your Xero account, or if the cache is cleared (e.g. `php artisan cache:clear`)

I'm contemplating writing the token out to the app storage so it's not affected by Laravels cache.

As for the $sid that sounds like it's coming directly from Xeros  package as we don't have any properties named that. Could you please share the stack trace?

**Comment by discoveryjames** [comment]
Hi @hailwood 

It seems that during that time, the Xero API continues to work as normal, so it must just be the way something is being fetched on that page.

I'll try and work out what's going wrong when it's looking up the details to show on that screen.

**Comment by hailwood** [comment]
No worries,

I'm going to close this issue for now, if you can find more details and comment then I'll reopen it :)

**Comment by accessTechnology** [comment]
Can confirm this error shows on the index function of the controller after a period of time (1hr?), xero calls do seem to continue to function though

![image](https://user-images.githubusercontent.com/55278705/82738942-87797b80-9d33-11ea-805e-018d174be4a0.png)

**Comment by a-tesh** [comment]
Contrary to the above, I have several scheduled commands (calling Xero) which fail if I have this message. I have to reconnect every hour or so.
