### ISSUE TITLE
Notice: Undefined index: oauth2state in  Application/XXX/XXX : Invalid State: 

### ISSUE THREAD

**Issue by kunallibra** [webfox/laravel-xero-oauth2#35]
hi I am having this error [Error: 500]

My scopes in the authorised are:
$options = [
'scope' => ['openid email profile offline_access accounting.settings.read accounting.transactions accounting.contacts accounting.attachments']
];

and in the config file:

'scopes' => [
'openid',
'email',
'profile',
'offline_access',
'accounting.settings.read',
'accounting.transactions',
'accounting.contacts',
'accounting.attachments'
],

It is exactly the same. Dont know why am getting this error.

Notice: Undefined index: oauth2state in /Applications/XAMPP/xamppfiles/htdocs/project/callback.php on line 24
Invalid StateInvalid state

**Comment by hailwood** [comment]
Hi @kunallibra,

Are you sure you're using this Laravel integration and not just the [XeroAPI/xero-php-oauth2](https://github.com/XeroAPI/xero-php-oauth2) package?

I'd expect to see a Laravel path there if you're using this package, e.g. `/Applications/XAMPP/xamppfiles/htdocs/project/app/Http/Controllers/SomeController.php`.

I'm going to close this issue as I don't believe it's related to this package, but feel free to comment if you wish it reopened.
