### ISSUE TITLE
Xero credentials do not exist in the redirect URL

### ISSUE THREAD

**Issue by C-Collamar** [webfox/laravel-xero-oauth2#36]
Hi!

After the Xero authorization server redirects back to my `xero.auth.success` endpoint with the authorization code and all, the injected `OauthCredentialManager $xeroCredentials` in the receiving controller method returns `false` at `$xeroCredentials->exists()`.

Here's the code (got it from your [documentation][1]):

```php

<?php

namespace App\Http\Controllers\integrations;

use App\Http\Controllers\Controller;
use Webfox\Xero\OauthCredentialManager;
use App\XeroCredentials;
use Illuminate\Http\Request;

class XeroController extends Controller
{
    public function index(Request $request, OauthCredentialManager $xeroCredentials)
    {
        try {
            if ($xeroCredentials->exists()) { // 👈 returns `false`

```

[1]: https://github.com/webfox/laravel-xero-oauth2#using-the-package

**Comment by hailwood** [comment]
Hi @C-Collamar,

Could you setup a simple reproduction as a git repo?
Don't worry about the api keys, I'll use mine, just need the code :+1:

**Comment by C-Collamar** [comment]
Here's a simple repo that reproduces this issue: https://github.com/C-Collamar/laravel-xero-oauth2-bug-reprod

the `auth.xero.success` points to the `/test` web route. Here's the response:

```http
HTTP/1.1 200 OK
Host: localhost
X-Powered-By: PHP/7.4.6
Content-Type: application/json

{
  "connected": false,
  "error": null,
  "organisationName": null,
  "username": null
}
```

**Comment by C-Collamar** [comment]
Nevermind. I just realized the redirect URI that I had set up in the Xero developer portal does not point to the `/xero/auth/callback` route as mentioned in the documentation. Missed that part in the documentation. Would be nice if it was highlighted a little bit more. 

Anyway thanks!
