### ISSUE TITLE
Credentials not refreshed on first load

### ISSUE THREAD

**Issue by Daafie** [webfox/laravel-xero-oauth2#37]
Hi

When my App is idle (no Xero API calls for 30 minutes), I receive the Token expired error on my first API call. The next API call will then be fine again and every call thereafter works (if the App did not go idle for 30 minutes again). Therefore it would seem that the token refresh is working, except for the first call after being idle.

As I understand, when the '\XeroAPI\XeroPHP\Api\AccountingApi::class' gets resolved, the tokens will be refreshed. My implementation saves the tokens to the database and uses a Middleware to register the credentials. I am using Method injection in the Controller to resolve the AccountingApi class. I am just providing broad details as I am not sure where or what is causing this.

I am trying to resolve this, but not getting far as I need to wait 30 minutes before I can test it and then everything is working fine again.

Any help or ideas would be appreciated.

**Comment by hailwood** [comment]
Hi Daafie,
So the 30 minutes will be the initial token expiring as that's how long they live,
After that it should be using the refresh token to fetch a new token whenever you resolve the Credential class (which is resolved by the AccountingApi) - https://github.com/webfox/laravel-xero-oauth2/blob/master/src/XeroServiceProvider.php#L63-L69

Can I please see your custom CredentialManager?

**Comment by Daafie** [comment]
Hi @hailwood 

Thanks for responding. I got this to work by updating my data function in my Credential Manager to get a 'fresh' copy of the user. Without the fresh(), it seems to be using the previous token.

`    protected function data($key = null)
    {
        if (!$this->exists()) {
            throw new \Exception('Xero oauth credentials are missing');
        }

        $data = $this->user->fresh()->xeroAccessToken->toArray();

        return empty($key) ? $data : ($data[$key] ?? null);
    }
`
