### ISSUE TITLE
JWTClaims decoded object does not contain sid key

### ISSUE THREAD

**Issue by conormx** [webfox/laravel-xero-oauth2#39]
![Screen Shot 2020-11-02 at 5 40 28 pm](https://user-images.githubusercontent.com/50386432/97841974-988ed580-1d32-11eb-81cc-f64146b005aa.png)

Please note the screenshot of the decoded JWT object returned from the Xero API.

It is causing this output in your example connection management page:

![Screen Shot 2020-11-02 at 5 42 07 pm](https://user-images.githubusercontent.com/50386432/97842105-cd029180-1d32-11eb-839f-073b36c1d0de.png)

Any other request is working, though. Very strange.

Please let me know ANY further information I can provide you to assist in understanding what is occurring happy to put in a PR if we can determine the right path here.

**Comment by hailwood** [comment]
Hi @conormx,

Thanks for reporting this,
You're not the first person to run into this it seems https://github.com/XeroAPI/xero-php-oauth2/issues/150

Looking into it, our code is almost identical to what they're using in the examples, one line sticks out to me though.
I see they [set the token access property before decoding](https://github.com/XeroAPI/xero-php-oauth2-starter/blob/26f7a8ed2ebd76e449748359611498692bbd72a1/authorizedResource.php#L164) and we don't.

Could you please update your copy locally to add `$jwt->setTokenAccess($this->data('token'));` both between [these lines](https://github.com/webfox/laravel-xero-oauth2/blob/master/src/Oauth2CredentialManagers/FileStore.php#L108-L109)
and [these lines](https://github.com/webfox/laravel-xero-oauth2/blob/master/src/Oauth2CredentialManagers/CacheStore.php#L106-L107) (so updating both the credential managers) and then check if that fixes your issue?



Cheers,
Matt

**Comment by conormx** [comment]
Hi @hailwood,

That has resolved the issue and I'll shortly submit a PR!

Thank you! :)

**Comment by conormx** [comment]
Ah, I misspoke!

Apologies @hailwood this didn't fix it. However I've noticed that sid is not used other than setting it (where it fails). I'm going to PR commenting it out and see where I get! Apologies.

**Comment by conormx** [comment]
I've sent a PR and commented on the issue over here: https://github.com/XeroAPI/xero-php-oauth2/issues/150

**Comment by conormx** [comment]
This has been merged and released upstream @hailwood :) https://github.com/XeroAPI/xero-php-oauth2/issues/150#issuecomment-724373096
