### ISSUE TITLE
getRefreshToken() must be of the type string, null returned

### ISSUE THREAD

**Issue by chintanmahant** [webfox/laravel-xero-oauth2#42]
When i perfom callback url then get this error Return value of Webfox\Xero\Oauth2CredentialManagers\FileStore::getRefreshToken() must be of the type string, null returned

my callback url is https://{your-domain}/xero/auth/callback

Please help me.

**Comment by hailwood** [comment]
Hmm that sounds like you've somehow gotten an expired access token but no refresh token stored.
I have no idea how you'd get into that situation sorry!

Does it happen if you delete the /storage/framework/xero.json file and reconnect?

**Comment by chintanmahant** [comment]
@hailwood 
Thanks for replay. Solve this issue by delete the /storage/framework/xero.json file
But then how to access API. i read example document but no idea how to implement this. 
Do you have any example.

**Comment by hailwood** [comment]
Hi @chintanmahant,

Did you try reconnecting after deleting that file as mentioned above?

**Comment by bilalswiftsolutions** [comment]
@hailwood  yes it is solving our issue we can reconnect it . But the problem is there about hundred of invoices we are uploading automatically on daily basis and have no idea why it gets disconnect or invalid_grant error. after reconnecting it we are uploading those invoice on xero manually which is headache . is there any solution where can permanently connect xero?

**Comment by chintanmahant** [comment]
Yes, ut's working.
*Thanks & Regards, *



*Nivida Web Solutions Private Limited*

*Consulting | **Design | Develop | Mobile Apps | Market | Host | Products |
SaaS | Cyber Security*

*GSTIN:* 24AAECN4256C1ZT
*PAN: *AAECN4256C
*WEBSITE: *www.nivida.in
----------------------------------------------------------------------------------
*INDIA* *USA & Canada*
Reg. Office: 201 East 5th Street, Suite 1200
315 Atlantis, Opp Vadodara Central Mall Sheridan, WY 82801
Sarabhai Road, Vadodara-390007 *Phone:* (415)-315-9698
Gujarat, India *Email:* sales@nivida.in
*Corporate Office:*
305 A/B Privilege Avenue
Opp. Isha Hospital
Sarabhai Road, Vadodara 390007
Gujarat, India
*Phone:* +91-9825530124, 8140088833/90
*Email:* sales@nivida.in
-----------------------------------------------------------------------------------
*Support: *+91-8140088840/50/60/70
-----------------------------------------------------------------------------------
*Accounts, Career & General **Inquires**: *www.nivida.in/contact-us

Information Disclaimer: This email and any/all files data, or information
transmitted with it are privileged and strictly confidential and intended
solely for the use of the individual or entity to whom they are
addressed/the recipient. If you are not the intended recipient or an agent
acting in course of due discharge of duties and thereby responsible for
delivering it to the intended recipient, you are hereby notified that you
have received this email in error/mistake and you are prohibited to review,
disseminate, distribute, copy or use this e-mail, its contents or any
attachments contained herein and thereby please notify the sender
immediately by e-mail and delete this e-mail from your system to ensure
avoidance of such mistake. It is strictly forbidden to share any part of
this message with any third party, without written consent of the sender.
Nivida Web Solutions Private Limited places the security of recipients of
this email at highest priority. Therefore, we have put effort into ensuring
that the message is totally and completely free from error, contamination,
interception, and/or virus. However, E-mail transmissions cannot be
guaranteed to be secure or error-free as data, files, attachments,
information could be intercepted, infected, corrupted, lost, destroyed,
arrive late or incomplete, or contain viruses. Therefore, the recipient
should check the email and allied files, data, documents, attachments, etc
for threats with proper software, as the sender/ Nivida Web Solutions
Private Limited does not accept liability for any errors or omissions in
the contents, data, information, attachments of this message and the
consequential damage, loss, etc of any nature arising as a result of e-mail
transmission. The sender Nivida Web Solutions Private Limited also confirms
that it shall not be responsible if this email message is used for any
breach of confidentiality and privacy, indecent, indecent, unsolicited or
illegal purposes, which violate any existing laws, rules, regulations,
policy, statutes, directions, notifications, circulars and the same shall
solely be the responsibility of misuser/recipient/ its agent and that the
sender shall at all times be indemnified of any civil and/ or criminal
liabilities or consequences thereof. If verification of email and/or its
content is required please requisition a hard-copy version that being
subjected to internal regulations, policy, and guidelines of the Nivida Web
Solutions Private Limited may be provided.  Is it really necessary to print
this email? Let's join hands and contribute in nurturing mother Nature,
saving it from deforestation and keeping it Green and Clean by not printing
this email until necessary and of utmost importance.
