### ISSUE TITLE
When i connect with any get response 401.

### ISSUE THREAD

**Issue by chintanmahant** [webfox/laravel-xero-oauth2#43]
When i connect any API then get 401 response LIKE, 

[401] Client error: `GET https://api.xero.com/api.xro/2.0/BankTransfers` resulted in a `401 Unauthorized` response: {"Type":null,"Title":"Unauthorized","Status":401,"Detail":"AuthorizationUnsuccessful","Instance":"ff714886-df24-4822-b64 (truncated...)

public function getInvoice(Request $request, OauthCredentialManager $xeroCredentials){        
        $apiInstance = resolve(\XeroAPI\XeroPHP\Api\AccountingApi::class);
        $xeroTenantId = $xeroCredentials->getTenantId();
       $str = '';
        $result = $apiInstance->getBankTransfers($xeroTenantId); 
        $str = $str . "Get BankTransaction total: " . count($result->getBankTransfers()) . "<br>";
ead]
            echo $str; die;
      
    }

**Comment by hailwood** [comment]
Sorry @chintanmahant,

There's not really anything actionable here,
For some reason the API is responding that you're not authorized. Perhaps the token has been revoked?
