### ISSUE TITLE
PHP8 support?

### ISSUE THREAD

**Issue by ok200paul** [webfox/laravel-xero-oauth2#44]
**Is your feature request related to a problem? Please describe.**
The composer.json file has the restriction set for `^7.3` environments

**Describe the solution you'd like**
Support for PHP8 environments

**Describe alternatives you've considered**
- Downgraded local dev environment back to PHP7.4
- Held off upgrading production environments to PHP8

**Additional context**
This is one of the few packages left in our application that is restricting us from moving up to PHP8. I've cloned the package and taken a look through the code, and from a 30-minute look (no testing), my IDE (PHPStorm set to PHP8 syntax) doesn't bark about any syntax issues. I'll see about popping a PR that covers this, some time this week - hopefully it helps!

**Comment by hailwood** [comment]
Hi @ok200paul,

We don't yet have any PHP8 projects, but I believe we're not using any features that would be deprecated in PHP8 so I've gone ahead and done a release (2.0.4) with the composer requirements updated.

Please comment back here if you run into any issues.


Cheers!

**Comment by ok200paul** [comment]
Thanks so much @hailwood - appreciate it! I'll keep a close eye.
