### ISSUE TITLE
[BUG] redirect uri is using http instead of https

### ISSUE THREAD

**Issue by Childplan** [webfox/laravel-xero-oauth2#47]
**Describe the bug**
When using this package to develop on my local machine using Valet Share, the redirect_uri defaults to the http connection rather than the https.  

Relevant part of URL passed to Xero:
&approval_prompt=auto&redirect_uri=**http**%3A%2F%2Fcafa1ddXXXXX.ngrok.io

This results in a 'Error: unauthorized_client : Invalid redirect_uri' error when establishing a connection

**Expected behavior**
That redirect_uri would default to a https connection, as this is the only connection accepted by Xero

**Screenshots**

<img width="301" alt="image" src="https://user-images.githubusercontent.com/30173261/104808738-1ef48700-584d-11eb-9021-cb2ba1fbaf57.png">

<img width="167" alt="image" src="https://user-images.githubusercontent.com/30173261/104808721-0b492080-584d-11eb-9642-083e8a532d64.png">

**Comment by Childplan** [comment]
Please note, I am not saying that the above is a bug - possibly user error on my part so apologies if that's the case :)

**Comment by hailwood** [comment]
Hi @Childplan,

Can you please check your APP_URL in your .env file? Is that http or https?

**Comment by Childplan** [comment]
Thanks for the quick response.
  
I have updated the APP_URL to point to my local server (https://xxxx.ngrokxx.io), but the same issue.
  
If I manually change the URL sent to Xero to https then I can connect successfully.

**Comment by Childplan** [comment]
OK - bit of digging and found the issue, along with fix / work around.
The issue relates to the Laravel project not enforcing HTTPS connection, unless the following is added to the AppServiceProvider:

<img width="182" alt="image" src="https://user-images.githubusercontent.com/30173261/104827186-20ab6280-58c0-11eb-8743-789057a50a10.png">

Once added, the issue is resolved.
