### ISSUE TITLE
How to check xero credentials are exist globally?

### ISSUE THREAD

**Issue by bilalswiftsolutions** [webfox/laravel-xero-oauth2#49]
is there any way we can check that if xero credentials are exists or not? 

Actually I want to check it in laravel blade file. but not in one file but all files. so I cant return it from every controller. So I am checking way if I can get it in blade directly?

**Comment by hailwood** [comment]
Either

a. [Inject an instance](https://laravel.com/docs/8.x/blade#service-injection) of `\Webfox\Xero\OauthCredentialManager` and then call `$credentials->exists()`
b. Use a [view composer](https://laravel.com/docs/8.x/views#view-composers) and tell it to compose `'*'` so it applies to all views.

**Comment by bilalswiftsolutions** [comment]
I tried this but getting this error

```
Illuminate\Contracts\Container\BindingResolutionException
Target [\Webfox\Xero\OauthCredentialManager] is not instantiable. (View: C:\projects\coldxlogistics\resources\views\web\admin\layouts\index.blade.php)
```

Thats how I tried
```
@inject('credentials', '\Webfox\Xero\OauthCredentialManager')
@dd($credentials->exists())
```
