### ISSUE TITLE
Undefined offset on Auth

### ISSUE THREAD

**Issue by andrewgoodnz** [webfox/laravel-xero-oauth2#5]
When trying to Authorise I get the following error on the callback.
![Annotation 2020-04-15 125521](https://user-images.githubusercontent.com/8357667/79287617-78bfcd80-7f18-11ea-81e9-542dab6dcf3e.png)

**Comment by hailwood** [comment]
Hmm, that should only happen if you manage to authenticate as a user who is part of no Organisations since `$identity->getConnections()` is meant to give you a list of organisations the access to is valid for.

**Comment by andrewgoodnz** [comment]
Any thoughts on how to debug this further? I Have logged in with the usual credentials I use to access my Xero account and there is definitely an Organisation there!

**Comment by hailwood** [comment]
I would suggest either (temporarily) editing the vendor files and dump out `$identity->getConnections()` to see what response you're getting, or trace it through with xDebug.

Please do share the response, since this does sound like a bug and I'd like to fix it if we can :)

**Comment by andrewgoodnz** [comment]
Thanks @hailwood, turns out I didnt have the scopes set properly in `config/xero.php`

So I am now 1 step ahead but still not quite there...  I now get a 401 Unauthorized on the callback.

![Annotation 2020-04-16 123032](https://user-images.githubusercontent.com/8357667/79401794-31037980-7fde-11ea-87a4-98edcd871c3c.png)

**Comment by hailwood** [comment]
Based off the endpoint, I'd say that's failing at 

```php
$organisationName = $xero->getOrganisations($xeroCredentials->getTenantId())->getOrganisations()[0]->getName();
```

What scopes are you using?

**Comment by andrewgoodnz** [comment]
Yep, seems fair to say its failing at this line.
`
 'scopes'=> [
    'openid',
    'email',
    'profile',
    'offline_access',
    'accounting.contacts',
    'accounting.transactions',
],
`

**Comment by hailwood** [comment]
They seem fine, 

Do you get the same result if you attempt to reconnect?

**Comment by andrewgoodnz** [comment]
Yes, same result on reconnect...

**Comment by a-tesh** [comment]
@andrewgoodnz Can you try including the 'accounting.settings' scope and reconnect?

**Comment by sergomet** [comment]
@andrewgoodnz I hade the same issue, after adding 'accounting.settings' it works. 
Thanks @a-tesh

**Comment by hailwood** [comment]
Thanks for Chiming in @a-tesh.
Is there ever a time you wouldn't want that scope?
I might force it into the list to avoid this issue
