### ISSUE TITLE
JSON request body could not be read

### ISSUE THREAD

**Issue by deemonic** [webfox/laravel-xero-oauth2#50]
**Describe the bug**

Has anyone used this package to generate an invoice in Xero? I keep getting the following error

XeroAPI\XeroPHP\ApiException: [400] Client error: `PUT https://api.xero.com/api.xro/2.0/Invoices?summarizeErrors=false` resulted in a `400 Bad Request` response:
{
  "ErrorNumber": 14,
  "Type": "PostDataInvalidException",
  "Message": "JSON request body could not be read, Error (truncated...)
 in file C:\inetpub\sites\webhooks.crystallegal.com\vendor\xeroapi\xero-php-oauth2\lib\Api\AccountingApi.php on line 7453

I can see in the AccountingApi.php file that the request is serialize as JSON

**To Reproduce**

I have successfully done the follwing

1. Created an oAuth2.0 instance (This is working)
2. Added the required scopes for Contacts and Invoices in the Xero.php config file and re-connected my app using oAuth 2.0
3. I have succussfulyl created a contact in Xero using the API and return the contact ID which is used for the Invoice request
4. Create a LineItems object as at least 1 Line item is required to create an invoice

Here is my method

    public function createInvoice(Request $request, OauthCredentialManager $xeroCredentials)
    {

        $arr_invoices = [];

        $lineitems = [];
        array_push($lineitems, $this->getLineItem());

        $invoice = new Invoice();
        $invoice->setReference('Ref-' . $request->matter_id)
            ->setDueDate(Carbon::now())
            ->setContact($this->getContact($xeroCredentials))
            ->setLineItems($lineitems)
            ->setStatus(Invoice::STATUS_AUTHORISED)
            ->setType(Invoice::TYPE_ACCPAY)
            ->setLineAmountTypes(\XeroAPI\XeroPHP\Models\Accounting\LineAmountTypes::EXCLUSIVE);

        array_push($arr_invoices, $invoice);

        $invoices = new Invoices();
        $invoices->setInvoices($arr_invoices);

       //dd($invoices);

        $result = $this->apiInstance->createInvoices($xeroCredentials->getTenantId(), $invoices);

        dd($result);
    }

**Expected behavior**

I would expect this to create an Invoice as I believe I have followed instructions form this package as well as the Xero documentation

**Comment by hailwood** [comment]
Is there any way for you to share the non-truncated error?

I suggest you also submit this issue to https://github.com/XeroAPI/xero-php-oauth2 as this appears to be more API usage related rather than authentication related.

**Comment by deemonic** [comment]
I will take a look and see if I can find another error.

I will raise this issue on the repo you provided too, thanks for the response
