### ISSUE TITLE
How to connect xero with api request?

### ISSUE THREAD

**Issue by bilalswiftsolutions** [webfox/laravel-xero-oauth2#51]
Actually, we can't afford the disconnection of the Xero app. Now I want to use corn job in order to connect my app with Xero. 
The idea is cronjob will check the connection after few minutes. if Xero is disconnected it will try to connect it again,.

Now the issue is We can connect Xero app with GUI by following certain steps? Is there any kind of APIs by which we can connect it again?

**Comment by hailwood** [comment]
Nope, the only way to connect is via the Oauth2 flow.

Honestly, given the number of issues you seem to be having with this package, I'm going to recommend giving https://github.com/calcinai/xero-php a go which is also a fantastic package. 

It would be interesting to know if you run into the same issues with that package.
