### ISSUE TITLE
Storing and accessing credentials from database instead of filestorage.

### ISSUE THREAD

**Issue by abhimanusharma** [webfox/laravel-xero-oauth2#52]
Many deployment server won't allow access to symlinks and thus create issues storing and retrieving credentials from storage. 
Even if this is not the case, storing and accessing credentials in database would be much more efficient and does not require any special permissions.

If this is already possible in this package then please add it in the documentation, if not then please add this feature in this package. 

Requirement: my requirement is for multi admin system where all admin will have their own xero credential which they can add in the system and access their own xero account data.

**Comment by hailwood** [comment]
The credentials are **not** stored in the publically accessible storage so the symlinks have no bearing on this package.

You have full control on how you'd like to store the credentials, for an example of how you'd store them in the database on a per-user basis please see this issue https://github.com/webfox/laravel-xero-oauth2/issues/45#issuecomment-757552563.


Cheers
