### ISSUE TITLE
Intent To Receive

### ISSUE THREAD

**Issue by marcodeluca** [webfox/laravel-xero-oauth2#54]
Hey, trying to configure webhooks but no matter what I do when trying to complete the "Intent To Receive" from xero's developer portal, I get "Response not 200" or "Response contains a body". I've tried all sorts of things like:

response('', Response::HTTP_OK)
abort(200);
return response()->noContent()
etc

Any suggestions?

**Comment by marcodeluca** [comment]
Ok so the file as is works, the the issue was debug has to be FALSE in the env. If debug is true, the intent to receive will fail.

**Comment by hailwood** [comment]
Interesting, thanks for the followup.

I suspect you'll have a package like laravel-debug-bar installed that would be automatically appending itself to the response.
