### ISSUE TITLE
 local.ERROR: Invalid response received from Authorization Server. Expected JSON

### ISSUE THREAD

**Issue by ramay2088** [webfox/laravel-xero-oauth2#55]
**Describe the bug**
I am checking Xero connection availability  like this
```
   $xeroSettings = \App::make('Webfox\Xero\OauthCredentialManager');
   $xeroSettings->exists();
```
but I am using it in file which is common throughout the website.  so yesterday after 5 months I don't know why it starts giving this error

```
local.ERROR: Invalid response received from Authorization Server. Expected JSON. {"exception":"[object] (UnexpectedValueException(code: 0): Invalid response received from Authorization Server
```

Because of which it gives error on all pages of the website so I start receiving complains from our customers.  
I checked the xero.json file. File was present and key inside the was also present

After that when I deleted the xero.json file error was gone but I have to reconnect with the Xero account. 

Can you please let me know why it was happening? 

At least how i can avoid this error on all the pages?

**To Reproduce**
I think you can reproduce this error by giving random string in xero.json file

**Expected behavior**
It should not give that error instead it can tell us that Xero connection doesn't exist

**Comment by hailwood** [comment]
#53
