### ISSUE TITLE
redirectUri is using incorrect value if xero.oauth.redirect_full_url is set

### ISSUE THREAD

**Issue by mforcer** [webfox/laravel-xero-oauth2#56]
If `xero.oauth.redirect_full_url` is set to `true` as suggested in the config file, `redirectUri` is set to use this specific value (i.e `true`) therefore the `redirect_uri `sent to Xero is the value `1`.

A quick fix is setting `redirect_full_url` to the actual URL, meaning an update to the description in the config will clear this up.

Alternatively, a change to the ternary statement is needed.

```
'redirectUri'  => config('xero.oauth.redirect_full_url') ? 
        config('xero.oauth.redirect_uri') : route(config('xero.oauth.redirect_uri')),
```

https://github.com/webfox/laravel-xero-oauth2/blob/6c55b1935045e431b40c9cc56ee8e28bfb23bcac/src/XeroServiceProvider.php#L45

**Comment by hailwood** [comment]
Fixed in 2.0.7
