### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\build_query()

### ISSUE THREAD

**Issue by royallife88** [webfox/laravel-xero-oauth2#58]
I am using this package to connecting with Xero API. I installed the app on shared hosting and install the dependencies. When I allow the permission for Xero organization, on redirect, it shows the guzzle relate error. please look at the screenshot below:

**To Reproduce**
Just follow the package readme steps.

**Screenshots**
![Screenshot 2021-09-14 154520](https://user-images.githubusercontent.com/40221030/133244139-9c49416c-99bd-4b43-9cc1-7c115a97b310.png)

I tried the guzzle version 6.5.2, but it also shows the same error for missing uri_for() function.
Thank in advance,
Regards,

**Comment by hailwood** [comment]
Hi @royallife88,

The error is actually coming from the Xero library (which we pull in as a dependency).
Please see https://github.com/XeroAPI/xero-php-oauth2/issues/240

Looks like the short-term fix is to manually install `guzzlehttp/psr7` version `^1.8`.

**Comment by royallife88** [comment]
Thank you sir, it worked for me.
