### ISSUE TITLE
Change of filesystem

### ISSUE THREAD

**Issue by stevethomas** [webfox/laravel-xero-oauth2#66]
**Is your feature request related to a problem? Please describe.**
`FileStore` is hardcoded to a local disk implementation which doesn't work in load balanced scenarios like:
- multiple EC2s behind a load balancer
- Vapor, where every request runs on a different lambda, and CLI + queue run in isolation

By "doesn't work" I mean that xero.json only exists on the server that executed the oauth flow, and there is no affordance to access xero.json outside of the local filesystem. 

The Cache driver in some ways solves this problem given the cache would be shared across instances, but it is also ephemeral and is more than likely to go missing at some point.

**Describe the solution you'd like**
I did a copy paste of `FileStore` and changed only `Illuminate\Filesystem\Filesystem` to `Illuminate\Filesystem\FilesystemManager`. With this change we are just changing to the default configured filesystem, and locally the xero.json ends up in `storage/app` instead of `storage/framework`. On Vapor the default filesystem is an S3 bucket.

I am happy to open a PR for this but it seems fairly trivial and would also we breaking backwards compatibility unless implementing as a new Store. If implementing as a new Store, it would probably make sense to extend a common abstract class due to the similarities - but i'm not sure I see the benefit of keeping the `Illuminate\Filesystem\Filesystem` implementation at all.

Another consideration would be adding `disk` to the config, so that the developer could easily use different disks depending on the environment.

It might be best handled as a new major version given the breaking change.

**Describe alternatives you've considered**
Of course the Store implementation worked as intended and I was able to workaround the local filesystem limitation; I just feel it would be better to be able to use this package out of the box outside of a single server environment.

I think filesystem is the logical place to persist the Xero credentials, I don't think it would be worthwhile pursuing other Stores (at least for my use case).

**Additional context**
The only concern I have is that the developer might have made their S3 bucket public and therefore exposing xero.json to the world. On the other hand S3 buckets are private by default, and a simple readme disclaimer might help to warn the developer to make sure the file is not public.

**Comment by hailwood** [comment]
Hi @stevethomas,

I'm happy to release a major version if you submit a PR :)

I think a config option for the disk, defaulted to the `default` filesystem would be appropriate.
We should be able to store the file with a visibility of `private` as well which should help against accidental exposure.


Regards,
Matt

**Comment by stevethomas** [comment]
Nice idea on the `private` visibility, I have implemented in my PR: https://github.com/webfox/laravel-xero-oauth2/pull/67. 

Closing this issue, feel free to request any changes on the PR.
