### ISSUE TITLE
Authorization issue with multi tenant update

### ISSUE THREAD

**Issue by chrisGeonet** [webfox/laravel-xero-oauth2#72]
There appears to be an issue caused by the new multi-tenant storage feature.
In laravel-xero-oauth2/src/OauthCredentialManager.php the store method requires the tenant to be an array.
`public function store(AccessTokenInterface $token, array $tenants = null): void;`

But in laravel-xero-oauth2/src/Controllers/AuthorizationCallbackController.php when the store method is called, a string is being passed in.
`$tenantId = $identity->getConnections()[0]->getTenantId();
$oauth->store($accessToken, $tenantId);`

I've just reverted to version 3 and all is fine.

**Comment by AllanGallop** [comment]
I've created pull request #73 to fix this

**Comment by hailwood** [comment]
Fixed in 4.0.1 release
