### ISSUE TITLE
multi tenant webhook issue

### ISSUE THREAD

**Issue by deanace** [webfox/laravel-xero-oauth2#77]
i seem to experience a problem when a webhook is fired from xero and i have more than one tenant id connected to the app
it only completes the request to get the invoice for the very first company and the rest of the companies give them following error

_[404] Client error: `GET https://api.xero.com/api.xro/2.0/Invoices/{invoice unique number}` resulted in a `404 Not Found` response:
The resource you're looking for cannot be found_

has anyone else experienced this issue ?

**Comment by AbrahamBrookes** [comment]
Are you sure you are passing in the correct tenant ID to your invoices fetch call? Are you sure the invoice exists? If you're getting a 404 then that means the oauth has worked so maybe this question is more for the Xero Accounting API PHP github page since it's not really relevant to Oauth

**Comment by hailwood** [comment]
Are you sure you're passing the correct tenant ID through with the subsequent requests?
