### ISSUE TITLE
Return value of Webfox\Xero\Oauth2CredentialManagers\FileStore::getState() must be of the type string, null returned

### ISSUE THREAD

**Issue by undefinedzain** [webfox/laravel-xero-oauth2#79]
Hello, i used this package along with
"laravel/framework": "^8.75"

and got `Return value of Webfox\Xero\Oauth2CredentialManagers\FileStore::getState() must be of the type string, null returned`

when callback

**Comment by hailwood** [comment]
Hi @undefinedzain,
Unfortunately there's not enough information included in your request for me to help you properly.

I believe somehow you've gotten to the point where the app believes you've got credentials stored, but the credential file either doesn't exist, or is empty.

My suggestion would be to remove the file if it exists and attempt to reauthenticate.
