### ISSUE TITLE
Can we connect one app with multiple XERO account?

### ISSUE THREAD

**Issue by alpeshssit** [webfox/laravel-xero-oauth2#83]
My client has 4 XERO accounts which need to connect with one XERO app, But when i tried to connect, it will allow only one access token to one organization.

I've created app in one XERO account, I've connected to XERO. Now I want to connect another XERO account with same app, then it will override before connected account.

Can you please help me how can we connect multiple XERO account?

**Comment by hailwood** [comment]
It sounds like you'll want to [define a custom credential store](https://github.com/webfox/laravel-xero-oauth2#credential-storage) so you can store multiple sets of credentials and retrieve them as desired.

**Comment by alpeshssit** [comment]
> It sounds like you'll want to [define a custom credential store](https://github.com/webfox/laravel-xero-oauth2#credential-storage) so you can store multiple sets of credentials and retrieve them as desired.

Basically I want to keep one credential and want to connect multiple XERO organizations but each organizations have different XERO account.
