### ISSUE TITLE
Question: when does the token actually refresh?

### ISSUE THREAD

**Issue by rebbieboi** [webfox/laravel-xero-oauth2#87]
according to the doc it will refresh automatically, but when does it do that? Does it refresh when "\XeroAPI\XeroPHP\Api\AccountingApi::class" is triggered?

thank you!

**Comment by hailwood** [comment]
Hi @rebbieboi,

It's refreshed whenever the credential manager is resolved - which it is whenever you resolve pretty much any of the xero classes :)

https://github.com/webfox/laravel-xero-oauth2/blob/master/src/XeroServiceProvider.php#L57-L59
