### ISSUE TITLE
[BUG] Token expires on long running scripts

### ISSUE THREAD

**Issue by cannycookie** [webfox/laravel-xero-oauth2#88]
**Describe the bug**
I have a script that syncs contacts  to Xero which needs to run for a couple of hours due to Xero's rate limiting.

**To Reproduce**
when the script reaches 30 mins run time the access token expires.  I've added a fn in the script to refresh the token after each batch is processed but the oauth refresh function only updates the stored token on disk and not the one currently in memory.

**Expected behavior**
Token should be refreshed

Any suggestion on how to handle this? 

Many thanks if you can help

**Comment by hailwood** [comment]
Good question @cannycookie,

I would suggest you'll need to tell laravel's container to forget the resolved instance of the credential manager and the resolve the Accounting api instance from the container again fresh.

**Comment by cannycookie** [comment]
Thanks, I will try and re-resolve the class to see if it reloads.

**Comment by hailwood** [comment]
Hi @cannycookie,

I'm going to close this issue now.
If you'd like it reopened please tag me in a reply.
